"""Emit a Fusion 360 Python script (adsk.core / adsk.fusion) that rebuilds
the recognised extrusion structure as a real parametric timeline: one
sketch per slab profile on a construction plane at the slab height, an
Extrude (join) or Loft (join) per slab, Extrude (cut) for cross-axis holes.
Cones (countersinks) are emitted as Revolve cuts of a triangle profile.

Run inside Fusion: Utilities > Add-Ins > Scripts and Add-Ins > + (Script),
choose the .py, Run. Fusion works in centimetres internally, so every mm
value is divided by 10 in the script.

Not yet verified inside Fusion 360 itself.
"""
import numpy as np


def _cm(v):
    return round(float(v) / 10.0, 6)


def _pt3(p):
    return f"adsk.core.Point3D.create({_cm(p[0])}, {_cm(p[1])}, {_cm(p[2])})"


def _vec3(v):
    return f"adsk.core.Vector3D.create({float(v[0]):.6f}, {float(v[1]):.6f}, {float(v[2]):.6f})"


def _ring_lines(ring, indent, W, sk='sk'):
    """Sketch curves for a ring. `W(x, y)` maps the ring's 2-D frame to a
    3-D world point (mm); points are converted into the sketch's own space
    with sketch.modelToSketchSpace, so the sketch orientation Fusion picks
    for the construction plane does not matter."""
    def P(x, y):
        wx, wy, wz = W(x, y)
        return f"{sk}.modelToSketchSpace(adsk.core.Point3D.create({_cm(wx)}, {_cm(wy)}, {_cm(wz)}))"
    L = []
    if isinstance(ring, dict):
        c = ring['center']
        L.append(f"{indent}{sk}.sketchCurves.sketchCircles.addByCenterRadius({P(c[0], c[1])}, {_cm(ring['r'])})")
        return L
    for p in ring:
        a, b = p['p0'], p['p1']
        if p['type'] == 'line':
            L.append(f"{indent}{sk}.sketchCurves.sketchLines.addByTwoPoints({P(a[0], a[1])}, {P(b[0], b[1])})")
        else:
            from .profile_fit import _arc_mid
            m = _arc_mid(p)
            L.append(f"{indent}{sk}.sketchCurves.sketchArcs.addByThreePoints({P(a[0], a[1])}, {P(m[0], m[1])}, {P(b[0], b[1])})")
    return L


def _ring_area(ring):
    """Area (mm^2) of a fitted ring (arcs sampled)."""
    from shapely.geometry import Polygon
    from .profile_fit import _arc_mid
    if isinstance(ring, dict):
        return float(np.pi * ring['r'] ** 2)
    pts = []
    for p in ring:
        if p['type'] == 'line':
            pts.append(np.asarray(p['p0'], float))
        else:
            c, r = np.asarray(p['center'], float), float(p['r'])
            a0 = np.arctan2(p['p0'][1] - c[1], p['p0'][0] - c[0])
            a1 = np.arctan2(p['p1'][1] - c[1], p['p1'][0] - c[0])
            if p.get('ccw', True):
                while a1 <= a0:
                    a1 += 2 * np.pi
            else:
                while a1 >= a0:
                    a1 -= 2 * np.pi
            for a in np.linspace(a0, a1, 24, endpoint=False):
                pts.append(c + r * np.array([np.cos(a), np.sin(a)]))
    if len(pts) < 3:
        return 0.0
    return float(abs(Polygon(pts).area))


def _material_areas_cm2(rings):
    """Expected material area (cm^2) of each profile: outer minus holes."""
    out = []
    for outer, holes in rings:
        a = _ring_area(outer) - sum(_ring_area(h) for h in holes)
        out.append(round(a / 100.0, 6))
    return out


def emit_fusion_script(bodies_info, design_name='stlToSolid'):
    L = [
        '"""Generated by stlToSolid — rebuilds the recognised extrusion structure',
        'as native Fusion 360 sketches + extrudes/lofts/cuts (parametric timeline).',
        'Fusion API units are centimetres; values below are mm/10."""',
        'import adsk.core, adsk.fusion, traceback',
        '',
        '',
        'def _plane(root, origin, normal):',
        '    """Construction plane through origin (cm) with the given normal.',
        '    In a direct-modelling design any plane can be set directly; a',
        '    parametric design only accepts planes defined from geometry, so',
        '    there the plane is an offset of the origin plane perpendicular',
        '    to the normal (the normal must then be along X, Y or Z). Returns',
        '    (plane, sign): sign is -1 when the plane normal points against',
        '    `normal`, so extrude distances must be negated."""',
        '    planes = root.constructionPlanes',
        '    design = root.parentDesign',
        '    if design.designType == adsk.fusion.DesignTypes.DirectDesignType:',
        '        inp = planes.createInput()',
        '        inp.setByPlane(adsk.core.Plane.create(adsk.core.Point3D.create(*origin),',
        '                                              adsk.core.Vector3D.create(*normal)))',
        '        return planes.add(inp), 1.0',
        '    mags = [abs(c) for c in normal]',
        '    k = mags.index(max(mags))',
        '    if mags[k] < 0.9999:',
        "        raise RuntimeError('the extrusion axis %s is not along X, Y or Z; switch the design '",
        "                           'to direct modelling (Design Settings > Do not capture design '",
        "                           'history) and run the script again' % (tuple(round(c, 4) for c in normal),))",
        '    base = (root.yZConstructionPlane, root.xZConstructionPlane, root.xYConstructionPlane)[k]',
        '    target = sum(o * n for o, n in zip(origin, normal))     # signed distance along normal',
        '    for off in (target, -target):',
        '        inp = planes.createInput()',
        '        inp.setByOffset(base, adsk.core.ValueInput.createByReal(off))',
        '        pl = planes.add(inp)',
        '        g = pl.geometry',
        '        o = g.origin',
        '        d = (o.x * normal[0] + o.y * normal[1] + o.z * normal[2]) - target',
        '        if abs(d) < 1e-5:',
        '            n = g.normal',
        '            sign = 1.0 if (n.x * normal[0] + n.y * normal[1] + n.z * normal[2]) > 0 else -1.0',
        '            return pl, sign',
        '        pl.deleteMe()',
        "    raise RuntimeError('could not place a construction plane at %s' % (origin,))",
        '',
        '',
        'def _pick(sketch, expected_cm2, rel=0.03):',
        '    """Profiles whose area matches one of the expected material areas',
        '    (sketch.profiles also lists hole interiors as profiles)."""',
        '    out = adsk.core.ObjectCollection.create()',
        '    for i in range(sketch.profiles.count):',
        '        pr = sketch.profiles.item(i)',
        '        a = pr.areaProperties().area',
        '        if any(abs(a - e) <= rel * max(e, 1e-9) for e in expected_cm2):',
        '            out.add(pr)',
        '    if out.count == 0:',
        '        for i in range(sketch.profiles.count):',
        '            out.add(sketch.profiles.item(i))',
        '    return out',
        '',
        '',
        'def run(context):',
        '    ui = None',
        '    try:',
        '        app = adsk.core.Application.get()',
        '        ui = app.userInterface',
        '        design = adsk.fusion.Design.cast(app.activeProduct)',
        '        root = design.rootComponent',
        '        extrudes = root.features.extrudeFeatures',
        '        lofts = root.features.loftFeatures',
        '        revolves = root.features.revolveFeatures',
        '        newBody = adsk.fusion.FeatureOperations.NewBodyFeatureOperation',
        '        join = adsk.fusion.FeatureOperations.JoinFeatureOperation',
        '        cut = adsk.fusion.FeatureOperations.CutFeatureOperation',
        '        made_any = False',
    ]
    ind = '        '
    for bi, info in enumerate(bodies_info):
        if info.get('mode') != 'prismatic' or 'slabs' not in info:
            L.append(f"{ind}# body {bi + 1}: not recognised as an extrusion (import the STEP for it)")
            continue
        axis = np.asarray(info['axis'], float)
        xdir = np.asarray(info['xdir'], float)
        ydir = np.cross(axis, xdir)
        L.append(f"{ind}# ---- body {bi + 1} ----")
        L.append(f"{ind}AXIS = ({axis[0]:.6f}, {axis[1]:.6f}, {axis[2]:.6f})")
        L.append(f"{ind}first = True")

        def W_at(z):
            return lambda x, y: axis * z + xdir * x + ydir * y
        for si, slab in enumerate(info['slabs']):
            z0, z1 = slab['z0'], slab['z1']
            h = z1 - z0
            L.append(f"{ind}# slab {si}: {z0:.3f} .. {z1:.3f} mm ({slab.get('kind', 'extrude')})")
            L.append(f"{ind}pl, sgn = _plane(root, ({_cm(axis[0] * z0)}, {_cm(axis[1] * z0)}, {_cm(axis[2] * z0)}), AXIS)")
            L.append(f"{ind}sk = root.sketches.add(pl)")
            if slab.get('kind') == 'loft' and slab.get('loft'):
                ra, rb = slab['loft'][0], slab['loft'][1]
                for (oa, ha) in ra:
                    L += _ring_lines(oa, ind, W_at(z0), 'sk')
                    for x in ha:
                        L += _ring_lines(x, ind, W_at(z0), 'sk')
                L.append(f"{ind}pl2, _ = _plane(root, ({_cm(axis[0] * z1)}, {_cm(axis[1] * z1)}, {_cm(axis[2] * z1)}), AXIS)")
                L.append(f"{ind}sk2 = root.sketches.add(pl2)")
                for (ob, hb) in rb:
                    L += _ring_lines(ob, ind, W_at(z1), 'sk2')
                    for y in hb:
                        L += _ring_lines(y, ind, W_at(z1), 'sk2')
                L.append(f"{ind}pa = _pick(sk, {_material_areas_cm2(ra)})")
                L.append(f"{ind}pb = _pick(sk2, {_material_areas_cm2(rb)})")
                L.append(f"{ind}for pi in range(min(pa.count, pb.count)):")
                L.append(f"{ind}    li = lofts.createInput(newBody if first else join)")
                L.append(f"{ind}    li.loftSections.add(pa.item(pi))")
                L.append(f"{ind}    li.loftSections.add(pb.item(pi))")
                L.append(f"{ind}    li.isSolid = True")
                L.append(f"{ind}    lofts.add(li)")
                L.append(f"{ind}    first = False")
            else:
                for (outer, holes) in slab['rings']:
                    L += _ring_lines(outer, ind, W_at(z0), 'sk')
                    for hring in holes:
                        L += _ring_lines(hring, ind, W_at(z0), 'sk')
                L.append(f"{ind}profs = _pick(sk, {_material_areas_cm2(slab['rings'])})")
                L.append(f"{ind}ei = extrudes.createInput(profs, newBody if first else join)")
                L.append(f"{ind}ei.setDistanceExtent(False, adsk.core.ValueInput.createByReal(sgn * {_cm(h)}))")
                L.append(f"{ind}extrudes.add(ei)")
                L.append(f"{ind}first = False")
        for c in info.get('cross_cyls', []):
            ax = np.asarray(c['axis'], float)
            bx, by = c['basis']
            c3 = c['center2'][0] * np.asarray(bx) + c['center2'][1] * np.asarray(by)
            blind = c.get('blind', [False, False])
            e0 = 0.0 if blind[0] else 1.0
            e1 = 0.0 if blind[1] else 1.0
            p0 = c3 + ax * (c['h0'] - e0)
            depth = (c['h1'] - c['h0']) + e0 + e1
            L.append(f"{ind}# cross-axis hole r={c['r']:.3f} mm")
            L.append(f"{ind}pl, sgn = _plane(root, ({_cm(p0[0])}, {_cm(p0[1])}, {_cm(p0[2])}), ({ax[0]:.6f}, {ax[1]:.6f}, {ax[2]:.6f}))")
            L.append(f"{ind}sk = root.sketches.add(pl)")
            L.append(f"{ind}sk.sketchCurves.sketchCircles.addByCenterRadius("
                     f"sk.modelToSketchSpace(adsk.core.Point3D.create({_cm(p0[0])}, {_cm(p0[1])}, {_cm(p0[2])})), {_cm(c['r'])})")
            L.append(f"{ind}ei = extrudes.createInput(sk.profiles.item(0), cut)")
            L.append(f"{ind}ei.setDistanceExtent(False, adsk.core.ValueInput.createByReal(sgn * {_cm(depth)}))")
            L.append(f"{ind}extrudes.add(ei)")
        for c in info.get('cones', []):
            L.append(f"{ind}# cross-axis cone (countersink), half-angle {np.degrees(c['half_angle']):.1f} deg: "
                     f"add a Revolve cut or Hole feature manually; apex {np.round(c['apex'], 3).tolist()} mm, "
                     f"axis {np.round(c['axis'], 4).tolist()}, extent {c['h0']:.2f}..{c['h1']:.2f} mm from the apex")
        L.append(f"{ind}made_any = True")
    L += [
        f"{ind}if not made_any:",
        f"{ind}    ui.messageBox('stlToSolid: nothing to build (no body was recognised as an extrusion)')",
        '    except:',
        "        if ui:",
        "            ui.messageBox('stlToSolid script failed:\\n{}'.format(traceback.format_exc()))",
        '',
    ]
    return '\n'.join(L) + '\n'


def _spline_pts(pts, indent, sk='sk'):
    """ObjectCollection of sketch-space points for a fitted spline."""
    L = [f"{indent}pc = adsk.core.ObjectCollection.create()"]
    for p in pts:
        L.append(f"{indent}pc.add({sk}.modelToSketchSpace(adsk.core.Point3D.create({_cm(p[0])}, {_cm(p[1])}, {_cm(p[2])})))")
    return L


def emit_fusion_loft_script(bodies_info, design_name='stlToSolid'):
    """Fusion script for sliced-loft bodies: the manual Fusion workflow as a
    timeline. Per section a sketch on an offset construction plane holding
    one closed fitted spline per outline (holes included), per run a Loft
    (new body, then join) through the outer profiles, and for holes a Loft
    cut through the hole profiles. Fusion works in cm; points are mm/10.

    Verified against the API reference, not yet run inside Fusion:
    SketchFittedSplines.add(ObjectCollection) draws the spline, and closing
    it is done by repeating the first point at the end (the API has no
    isClosed property on the input; a fitted spline whose last point equals
    its first is closed and yields a profile).
    """
    L = [
        '"""Generated by stlToSolid — rebuilds a sliced loft as native Fusion 360',
        'section sketches + Loft features (parametric timeline): one sketch per',
        'section on an offset plane, one closed fitted spline per outline, one',
        'Loft per run of sections, holes cut by their own Loft.',
        'Fusion API units are centimetres; values below are mm/10."""',
        'import adsk.core, adsk.fusion, traceback',
        '',
        '',
    ]
    # reuse the plane helper of the prismatic script verbatim
    base = emit_fusion_script([])
    start = base.index('def _plane(')
    end = base.index('def _pick(')
    L.append(base[start:end].rstrip('\n'))
    L += [
        '',
        '',
        'def _profile_by_area(sketch, expected_cm2):',
        '    """The profile whose area is nearest the expected material area',
        '    (a sketch with an outline and a hole lists the ring and the hole',
        '    as profiles; the outer outline alone is what the Loft needs)."""',
        '    best, bd = None, None',
        '    for i in range(sketch.profiles.count):',
        '        pr = sketch.profiles.item(i)',
        '        d = abs(pr.areaProperties().area - expected_cm2)',
        '        if bd is None or d < bd:',
        '            best, bd = pr, d',
        '    return best',
        '',
        '',
        'def _spline_sketch(root, origin, normal, loops):',
        '    """Sketch on the plane through origin (cm) with one closed fitted',
        '    spline per loop (list of point tuples, cm). Returns the sketch."""',
        '    pl, _ = _plane(root, origin, normal)',
        '    sk = root.sketches.add(pl)',
        '    for pts in loops:',
        '        pc = adsk.core.ObjectCollection.create()',
        '        for p in pts:',
        '            pc.add(sk.modelToSketchSpace(adsk.core.Point3D.create(*p)))',
        '        pc.add(sk.modelToSketchSpace(adsk.core.Point3D.create(*pts[0])))',
        '        sk.sketchCurves.sketchFittedSplines.add(pc)',
        '    return sk',
        '',
        '',
        'def _loop_area_cm2(pts):',
        '    """Shoelace area of a closed 3-D loop (cm^2), via its own plane."""',
        '    n = len(pts)',
        '    if n < 3:',
        '        return 0.0',
        '    cx = sum(p[0] for p in pts) / n',
        '    cy = sum(p[1] for p in pts) / n',
        '    cz = sum(p[2] for p in pts) / n',
        '    sx = sy = sz = 0.0',
        '    for i in range(n):',
        '        a = pts[i]',
        '        b = pts[(i + 1) % n]',
        '        ax, ay, az = a[0] - cx, a[1] - cy, a[2] - cz',
        '        bx, by, bz = b[0] - cx, b[1] - cy, b[2] - cz',
        '        sx += ay * bz - az * by',
        '        sy += az * bx - ax * bz',
        '        sz += ax * by - ay * bx',
        '    return 0.5 * (sx * sx + sy * sy + sz * sz) ** 0.5',
        '',
        '',
        'def run(context):',
        '    ui = None',
        '    try:',
        '        app = adsk.core.Application.get()',
        '        ui = app.userInterface',
        '        design = adsk.fusion.Design.cast(app.activeProduct)',
        '        root = design.rootComponent',
        '        lofts = root.features.loftFeatures',
        '        newBody = adsk.fusion.FeatureOperations.NewBodyFeatureOperation',
        '        join = adsk.fusion.FeatureOperations.JoinFeatureOperation',
        '        cut = adsk.fusion.FeatureOperations.CutFeatureOperation',
        '        made_any = False',
    ]
    ind = '        '
    for bi, info in enumerate(bodies_info):
        if info.get('mode') != 'loft' or not info.get('runs'):
            L.append(f"{ind}# body {bi + 1}: not a sliced loft (import the STEP for it)")
            continue
        axis = np.asarray(info['axis'], float)
        L.append(f"{ind}# ---- body {bi + 1}: sliced loft along {info.get('axis_name', '?')}, "
                 f"{info['n_sections']} sections at {info['interval']} mm, {len(info['runs'])} run(s) ----")
        L.append(f"{ind}AXIS = ({axis[0]:.6f}, {axis[1]:.6f}, {axis[2]:.6f})")
        L.append(f"{ind}first = True")
        for ri, run in enumerate(info['runs']):
            secs = run['sections']
            if len(secs) < 2:
                L.append(f"{ind}# run {ri + 1}: a single section at {secs[0]['z']:.3f} mm; nothing to loft")
                continue
            n_holes = min(len(s['holes']) for s in secs)
            L.append(f"{ind}# run {ri + 1}: {run['z0']:.3f} .. {run['z1']:.3f} mm, {len(secs)} sections"
                     + (f", {n_holes} hole(s)" if n_holes else "")
                     + (" (ruled)" if run.get('ruled') else ""))
            L.append(f"{ind}outer = []")
            L.append(f"{ind}holes = [[] for _ in range({n_holes})]")
            for si, sec in enumerate(secs):
                z = sec['z']
                origin = axis * z
                loops = [sec['outer']] + list(sec['holes'][:n_holes])
                cm_loops = [[(_cm(p[0]), _cm(p[1]), _cm(p[2])) for p in lp] for lp in loops]
                L.append(f"{ind}loops = {cm_loops!r}")
                L.append(f"{ind}sk = _spline_sketch(root, ({_cm(origin[0])}, {_cm(origin[1])}, {_cm(origin[2])}), AXIS, loops)")
                L.append(f"{ind}sk.name = 'section {info.get('axis_name', 'z')}={z:.2f} mm'")
                L.append(f"{ind}outer.append(_profile_by_area(sk, _loop_area_cm2(loops[0]) - sum(_loop_area_cm2(h) for h in loops[1:])))")
                for hi in range(n_holes):
                    L.append(f"{ind}holes[{hi}].append(_profile_by_area(sk, _loop_area_cm2(loops[{hi + 1}])))")
            L.append(f"{ind}li = lofts.createInput(newBody if first else join)")
            L.append(f"{ind}for pr in outer:")
            L.append(f"{ind}    li.loftSections.add(pr)")
            L.append(f"{ind}li.isSolid = True")
            if run.get('ruled'):
                L.append(f"{ind}li.isTangentEdgesMerged = False")
            L.append(f"{ind}lofts.add(li)")
            L.append(f"{ind}first = False")
            L.append(f"{ind}for hp in holes:")
            L.append(f"{ind}    hi_ = lofts.createInput(cut)")
            L.append(f"{ind}    for pr in hp:")
            L.append(f"{ind}        hi_.loftSections.add(pr)")
            L.append(f"{ind}    hi_.isSolid = True")
            L.append(f"{ind}    lofts.add(hi_)")
        L.append(f"{ind}made_any = True")
    L += [
        f"{ind}if not made_any:",
        f"{ind}    ui.messageBox('stlToSolid: nothing to build (no sliced-loft body)')",
        '    except:',
        "        if ui:",
        "            ui.messageBox('stlToSolid loft script failed:\\n{}'.format(traceback.format_exc()))",
        '',
    ]
    return '\n'.join(L) + '\n'


def _prim_curves(prims, indent, sk='sk'):
    """Sketch curves for one fitted loop (lines, arcs, circle or splines)
    given as 3-D points in mm: each primitive carries 'p0'/'p1'/'mid' or
    'pts' already lifted to 3-D by the caller."""
    def P(p):
        return f"{sk}.modelToSketchSpace(adsk.core.Point3D.create({_cm(p[0])}, {_cm(p[1])}, {_cm(p[2])}))"
    L = []
    if isinstance(prims, dict):                   # full circle
        L.append(f"{indent}{sk}.sketchCurves.sketchCircles.addByCenterRadius({P(prims['center3'])}, {_cm(prims['r'])})")
        return L
    for p in prims:
        if p['type'] == 'line':
            L.append(f"{indent}{sk}.sketchCurves.sketchLines.addByTwoPoints({P(p['p0'])}, {P(p['p1'])})")
        elif p['type'] == 'arc':
            L.append(f"{indent}{sk}.sketchCurves.sketchArcs.addByThreePoints({P(p['p0'])}, {P(p['mid'])}, {P(p['p1'])})")
        else:
            L.append(f"{indent}pc = adsk.core.ObjectCollection.create()")
            for q in p['pts']:
                L.append(f"{indent}pc.add({P(q)})")
            L.append(f"{indent}{sk}.sketchCurves.sketchFittedSplines.add(pc)")
    return L


def emit_fusion_sections_script(sections):
    """Fusion script drawing one sketch per section: Create Mesh Section
    Sketch + Fit Curves to Mesh Section, done. `sections` is a list of
    {'origin': (mm), 'normal', 'name', 'loops': [(outer_prims3d, [hole_prims3d...])],
    'open': [prims3d, ...]} with the primitives' points already in 3-D mm
    (section_fit.lift_prims). Lines and arcs come out as real sketch lines
    and three-point arcs, a whole-circle loop as a circle, spline stretches
    as fitted splines that share their end points with their neighbours, so
    every closed loop yields a profile. 'open' chains (a leaky mesh) are
    drawn as they are, open, the way Fusion's own mesh section draws
    them."""
    L = [
        '"""Generated by stlToSolid — mesh section sketches (like Create Mesh Section',
        'Sketch + Fit Curves to Mesh Section): one sketch per plane, lines / arcs /',
        'circles where the outline is clean, fitted splines where it is not.',
        'Fusion API units are centimetres; values below are mm/10."""',
        'import adsk.core, adsk.fusion, traceback',
        '',
        '',
    ]
    base = emit_fusion_script([])
    L.append(base[base.index('def _plane('):base.index('def _pick(')].rstrip('\n'))
    L += [
        '',
        '',
        'def run(context):',
        '    ui = None',
        '    try:',
        '        app = adsk.core.Application.get()',
        '        ui = app.userInterface',
        '        design = adsk.fusion.Design.cast(app.activeProduct)',
        '        root = design.rootComponent',
    ]
    ind = '        '
    for si, sec in enumerate(sections):
        o = np.asarray(sec['origin'], float)
        n = np.asarray(sec['normal'], float)
        L.append(f"{ind}# ---- section {si + 1}: {sec.get('name', '')} ----")
        L.append(f"{ind}pl, _ = _plane(root, ({_cm(o[0])}, {_cm(o[1])}, {_cm(o[2])}), ({n[0]:.6f}, {n[1]:.6f}, {n[2]:.6f}))")
        L.append(f"{ind}sk = root.sketches.add(pl)")
        L.append(f"{ind}sk.name = {sec.get('name', f'section {si + 1}')!r}")
        for outer, holes in sec['loops']:
            L += _prim_curves(outer, ind)
            for h in holes:
                L += _prim_curves(h, ind)
        for chain in sec.get('open', []):
            L += _prim_curves(chain, ind)
    L += [
        f"{ind}ui.messageBox('stlToSolid: drew {len(sections)} section sketch(es)')",
        '    except:',
        "        if ui:",
        "            ui.messageBox('stlToSolid sections script failed:\\n{}'.format(traceback.format_exc()))",
        '',
    ]
    return '\n'.join(L) + '\n'


# ---------------------------------------------------------------------------
# x-ray: a stack of section sketches, data + a drawing loop

_XRAY_RUNTIME = """

def draw_prims(sketch, prims):
    \"\"\"Draw one fitted loop or open chain (3-D mm primitives) into `sketch`:
    real lines, three-point arcs, a circle for a whole-circle loop, fitted
    splines for spline stretches. Nothing here closes a chain: a loop
    closes because its primitives share end points, an open chain stays
    open. Returns the curve count.\"\"\"
    curves = sketch.sketchCurves

    def P(p):
        return sketch.modelToSketchSpace(
            adsk.core.Point3D.create(p[0] / 10.0, p[1] / 10.0, p[2] / 10.0))

    if isinstance(prims, dict):                      # full circle
        curves.sketchCircles.addByCenterRadius(P(prims['center3']), float(prims['r']) / 10.0)
        return 1
    n = 0
    for p in prims:
        if p['type'] == 'line':
            curves.sketchLines.addByTwoPoints(P(p['p0']), P(p['p1']))
        elif p['type'] == 'arc':
            curves.sketchArcs.addByThreePoints(P(p['p0']), P(p['mid']), P(p['p1']))
        else:
            pc = adsk.core.ObjectCollection.create()
            for q in p['pts']:
                pc.add(P(q))
            curves.sketchFittedSplines.add(pc)
        n += 1
    return n


def draw_section(sketch, sec):
    \"\"\"All loops (outer + holes) and open chains of one section. Returns
    the curve count.\"\"\"
    n = 0
    for outer, holes in sec['loops']:
        n += draw_prims(sketch, outer)
        for h in holes:
            n += draw_prims(sketch, h)
    for chain in sec.get('open', []):
        n += draw_prims(sketch, chain)
    return n


def _extrude_slice(root, sketch, dist_cm, bodies):
    \"\"\"Extrude every profile of `sketch` by `dist_cm` (signed, along the
    sketch normal), one profile at a time: joined to the bodies made so
    far when it touches one of them, a new body otherwise (a feature that
    appears mid-stack starts its own body; Fusion refuses a Join that
    touches nothing, and one such profile must not cost the slice).
    `bodies` is extended in place. Returns the number of profiles
    extruded. With Outline only the profiles are just the outer regions;
    otherwise inner loops are filled too.\"\"\"
    if sketch.profiles.count == 0:
        raise RuntimeError('no closed profile to extrude')
    ops = adsk.fusion.FeatureOperations
    ext = root.features.extrudeFeatures
    made = 0
    for i in range(sketch.profiles.count):
        prof = sketch.profiles.item(i)
        feat = None
        if bodies:
            try:
                inp = ext.createInput(prof, ops.JoinFeatureOperation)
                inp.setDistanceExtent(False, adsk.core.ValueInput.createByReal(dist_cm))
                inp.participantBodies = [b for b in bodies if b.isValid]
                feat = ext.add(inp)
            except Exception:
                feat = None
        if feat is None:
            inp = ext.createInput(prof, ops.NewBodyFeatureOperation)
            inp.setDistanceExtent(False, adsk.core.ValueInput.createByReal(dist_cm))
            feat = ext.add(inp)
            for k in range(feat.bodies.count):
                bodies.append(feat.bodies.item(k))
        made += 1
    return made


def run(context):
    ui = None
    prog = None
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface
        design = adsk.fusion.Design.cast(app.activeProduct)
        root = design.rootComponent
        n = len(SECTIONS)
        prog = ui.createProgressDialog()
        prog.isCancelButtonShown = True
        prog.show(TITLE, 'Sketch %v of %m', 0, n, 0)
        made, n_ext, cancelled, bodies, notes = 0, 0, False, [], []
        for i, sec in enumerate(SECTIONS):
            prog.progressValue = i
            adsk.doEvents()
            if prog.wasCancelled:
                cancelled = True
                break
            if not sec['loops'] and not sec.get('open'):
                continue                              # the plane misses the part
            origin_cm = tuple(c / 10.0 for c in sec['origin'])
            pl, sgn = _plane(root, origin_cm, tuple(sec['normal']))
            pl.name = 'plane ' + sec['name']
            sk = root.sketches.add(pl)
            sk.name = sec['name']
            sk.isComputeDeferred = True               # hundreds of curves, one recompute
            try:
                draw_section(sk, sec)
            finally:
                sk.isComputeDeferred = False
            made += 1
            if sec.get('extrude_mm'):
                try:
                    _extrude_slice(root, sk, sgn * sec['extrude_mm'] / 10.0, bodies)
                    n_ext += 1
                except Exception:
                    why = traceback.format_exc().strip().splitlines()[-1]
                    notes.append('%s: extrude failed: %s' % (sk.name, why))
        prog.hide()
        msg = 'stlToSolid %s: drew %d of %d section sketch(es)' % (TITLE, made, n)
        if cancelled:
            msg += ' (stopped)'
        if n_ext:
            msg += ', extruded %d' % n_ext
        if notes:
            msg += '\\n' + '\\n'.join(notes[:10])
        ui.messageBox(msg)
    except:
        if prog is not None:
            try:
                prog.hide()
            except Exception:
                pass
        if ui:
            ui.messageBox('stlToSolid X-Ray script failed:\\n{}'.format(traceback.format_exc()))
"""


def _xray_round(x, nd=4):
    """Plain lists / dicts of rounded floats for embedding in the script."""
    if isinstance(x, dict):
        return {k: _xray_round(v, nd) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [_xray_round(v, nd) for v in x]
    if isinstance(x, np.ndarray):
        return _xray_round(x.tolist(), nd)
    if isinstance(x, (float, np.floating)):
        return round(float(x), nd)
    if isinstance(x, (int, np.integer, str)) or x is None:
        return x
    return x


def emit_fusion_xray_script(sections, title='X-Ray'):
    """Fusion script for a stack of section sketches, the way the add-in
    does it: the sections are embedded once as data and a small loop draws
    them (one construction plane + one sketch each, curves drawn with
    compute deferred), with a progress dialog that can be cancelled.
    `sections` is a list of {'origin' (mm), 'normal', 'name', 'loops':
    [(outer_prims3d, [hole_prims3d...])], 'open': [prims3d...],
    'extrude_mm': None | signed mm} with the primitives' points already
    in 3-D mm (section_fit.lift_prims). A section with 'extrude_mm' set
    is extruded that far along its normal after drawing (every profile,
    joined to the slabs so far), so the stack comes out as solid slices."""
    data = []
    for i, sec in enumerate(sections):
        data.append(_xray_round({
            'name': sec.get('name', f'section {i + 1}'),
            'origin': list(sec['origin']), 'normal': list(sec['normal']),
            'loops': [[outer, list(holes)] for outer, holes in sec['loops']],
            'open': list(sec.get('open', [])),
            'extrude_mm': sec.get('extrude_mm'),
        }))
    L = [
        '"""Generated by stlToSolid — X-Ray: a stack of mesh section sketches (like',
        'Create Mesh Section Sketch + Fit Curves to Mesh Section for every slice at',
        'once): one construction plane and one sketch per section, lines / arcs /',
        'circles where the outline is clean, fitted splines where it is not.',
        'Fusion API units are centimetres; the data below is mm and is divided by',
        '10 when drawn."""',
        'import adsk.core, adsk.fusion, traceback',
        '',
        f'TITLE = {title!r}',
        '',
        '# one entry per section: name, origin (mm), normal, loops [[outer, [holes]]],',
        '# open chains, extrude_mm (None, or how far to extrude towards the next plane)',
        'SECTIONS = [',
    ]
    L += [f'    {e!r},' for e in data]
    L += [']', '', '']
    base = emit_fusion_script([])
    L.append(base[base.index('def _plane('):base.index('def _pick(')].rstrip('\n'))
    L.append(_XRAY_RUNTIME)
    return '\n'.join(L)
