"""Emit a Fusion 360 Python script (adsk.core / adsk.fusion) that rebuilds
the recognised extrusion structure as a real parametric timeline: one
sketch per slab profile on a construction plane at the slab height, an
Extrude (join) or Loft (join) per slab, Extrude (cut) for cross-axis holes.
Cones (countersinks) are emitted as Revolve cuts of a triangle profile.

Run inside Fusion: Utilities > Add-Ins > Scripts and Add-Ins > + (Script),
choose the .py, Run. Fusion works in centimetres internally, so every mm
value is divided by 10 in the script.

Not yet verified inside Fusion 360 itself.
"""
import numpy as np


def _cm(v):
    return round(float(v) / 10.0, 6)


def _pt3(p):
    return f"adsk.core.Point3D.create({_cm(p[0])}, {_cm(p[1])}, {_cm(p[2])})"


def _vec3(v):
    return f"adsk.core.Vector3D.create({float(v[0]):.6f}, {float(v[1]):.6f}, {float(v[2]):.6f})"


def _ring_lines(ring, indent, W, sk='sk'):
    """Sketch curves for a ring. `W(x, y)` maps the ring's 2-D frame to a
    3-D world point (mm); points are converted into the sketch's own space
    with sketch.modelToSketchSpace, so the sketch orientation Fusion picks
    for the construction plane does not matter."""
    def P(x, y):
        wx, wy, wz = W(x, y)
        return f"{sk}.modelToSketchSpace(adsk.core.Point3D.create({_cm(wx)}, {_cm(wy)}, {_cm(wz)}))"
    L = []
    if isinstance(ring, dict):
        c = ring['center']
        L.append(f"{indent}{sk}.sketchCurves.sketchCircles.addByCenterRadius({P(c[0], c[1])}, {_cm(ring['r'])})")
        return L
    for p in ring:
        a, b = p['p0'], p['p1']
        if p['type'] == 'line':
            L.append(f"{indent}{sk}.sketchCurves.sketchLines.addByTwoPoints({P(a[0], a[1])}, {P(b[0], b[1])})")
        else:
            from .rebuild import _arc_mid
            m = _arc_mid(p)
            L.append(f"{indent}{sk}.sketchCurves.sketchArcs.addByThreePoints({P(a[0], a[1])}, {P(m[0], m[1])}, {P(b[0], b[1])})")
    return L


def _ring_area(ring):
    """Area (mm^2) of a fitted ring (arcs sampled)."""
    from shapely.geometry import Polygon
    from .rebuild import _arc_mid
    if isinstance(ring, dict):
        return float(np.pi * ring['r'] ** 2)
    pts = []
    for p in ring:
        if p['type'] == 'line':
            pts.append(np.asarray(p['p0'], float))
        else:
            c, r = np.asarray(p['center'], float), float(p['r'])
            a0 = np.arctan2(p['p0'][1] - c[1], p['p0'][0] - c[0])
            a1 = np.arctan2(p['p1'][1] - c[1], p['p1'][0] - c[0])
            if p.get('ccw', True):
                while a1 <= a0:
                    a1 += 2 * np.pi
            else:
                while a1 >= a0:
                    a1 -= 2 * np.pi
            for a in np.linspace(a0, a1, 24, endpoint=False):
                pts.append(c + r * np.array([np.cos(a), np.sin(a)]))
    if len(pts) < 3:
        return 0.0
    return float(abs(Polygon(pts).area))


def _material_areas_cm2(rings):
    """Expected material area (cm^2) of each profile: outer minus holes."""
    out = []
    for outer, holes in rings:
        a = _ring_area(outer) - sum(_ring_area(h) for h in holes)
        out.append(round(a / 100.0, 6))
    return out


def emit_fusion_script(bodies_info, design_name='stl2prism'):
    L = [
        '"""Generated by stl2prism — rebuilds the recognised extrusion structure',
        'as native Fusion 360 sketches + extrudes/lofts/cuts (parametric timeline).',
        'Fusion API units are centimetres; values below are mm/10."""',
        'import adsk.core, adsk.fusion, traceback',
        '',
        '',
        'def _plane(root, origin, normal):',
        '    """Construction plane through origin (cm) with the given normal."""',
        '    inp = root.constructionPlanes.createInput()',
        '    inp.setByPlane(adsk.core.Plane.create(adsk.core.Point3D.create(*origin),',
        '                                          adsk.core.Vector3D.create(*normal)))',
        '    return root.constructionPlanes.add(inp)',
        '',
        '',
        'def _pick(sketch, expected_cm2, rel=0.03):',
        '    """Profiles whose area matches one of the expected material areas',
        '    (sketch.profiles also lists hole interiors as profiles)."""',
        '    out = adsk.core.ObjectCollection.create()',
        '    for i in range(sketch.profiles.count):',
        '        pr = sketch.profiles.item(i)',
        '        a = pr.areaProperties().area',
        '        if any(abs(a - e) <= rel * max(e, 1e-9) for e in expected_cm2):',
        '            out.add(pr)',
        '    if out.count == 0:',
        '        for i in range(sketch.profiles.count):',
        '            out.add(sketch.profiles.item(i))',
        '    return out',
        '',
        '',
        'def run(context):',
        '    ui = None',
        '    try:',
        '        app = adsk.core.Application.get()',
        '        ui = app.userInterface',
        '        design = adsk.fusion.Design.cast(app.activeProduct)',
        '        root = design.rootComponent',
        '        extrudes = root.features.extrudeFeatures',
        '        lofts = root.features.loftFeatures',
        '        revolves = root.features.revolveFeatures',
        '        newBody = adsk.fusion.FeatureOperations.NewBodyFeatureOperation',
        '        join = adsk.fusion.FeatureOperations.JoinFeatureOperation',
        '        cut = adsk.fusion.FeatureOperations.CutFeatureOperation',
        '        made_any = False',
    ]
    ind = '        '
    for bi, info in enumerate(bodies_info):
        if info.get('mode') != 'prismatic' or 'slabs' not in info:
            L.append(f"{ind}# body {bi + 1}: not recognised as an extrusion (import the STEP for it)")
            continue
        axis = np.asarray(info['axis'], float)
        xdir = np.asarray(info['xdir'], float)
        ydir = np.cross(axis, xdir)
        L.append(f"{ind}# ---- body {bi + 1} ----")
        L.append(f"{ind}AXIS = ({axis[0]:.6f}, {axis[1]:.6f}, {axis[2]:.6f})")
        L.append(f"{ind}first = True")

        def W_at(z):
            return lambda x, y: axis * z + xdir * x + ydir * y
        for si, slab in enumerate(info['slabs']):
            z0, z1 = slab['z0'], slab['z1']
            h = z1 - z0
            L.append(f"{ind}# slab {si}: {z0:.3f} .. {z1:.3f} mm ({slab.get('kind', 'extrude')})")
            L.append(f"{ind}pl = _plane(root, ({_cm(axis[0] * z0)}, {_cm(axis[1] * z0)}, {_cm(axis[2] * z0)}), AXIS)")
            L.append(f"{ind}sk = root.sketches.add(pl)")
            if slab.get('kind') == 'loft' and slab.get('loft'):
                ra, rb = slab['loft'][0], slab['loft'][1]
                for (oa, ha) in ra:
                    L += _ring_lines(oa, ind, W_at(z0), 'sk')
                    for x in ha:
                        L += _ring_lines(x, ind, W_at(z0), 'sk')
                L.append(f"{ind}pl2 = _plane(root, ({_cm(axis[0] * z1)}, {_cm(axis[1] * z1)}, {_cm(axis[2] * z1)}), AXIS)")
                L.append(f"{ind}sk2 = root.sketches.add(pl2)")
                for (ob, hb) in rb:
                    L += _ring_lines(ob, ind, W_at(z1), 'sk2')
                    for y in hb:
                        L += _ring_lines(y, ind, W_at(z1), 'sk2')
                L.append(f"{ind}pa = _pick(sk, {_material_areas_cm2(ra)})")
                L.append(f"{ind}pb = _pick(sk2, {_material_areas_cm2(rb)})")
                L.append(f"{ind}for pi in range(min(pa.count, pb.count)):")
                L.append(f"{ind}    li = lofts.createInput(newBody if first else join)")
                L.append(f"{ind}    li.loftSections.add(pa.item(pi))")
                L.append(f"{ind}    li.loftSections.add(pb.item(pi))")
                L.append(f"{ind}    li.isSolid = True")
                L.append(f"{ind}    lofts.add(li)")
                L.append(f"{ind}    first = False")
            else:
                for (outer, holes) in slab['rings']:
                    L += _ring_lines(outer, ind, W_at(z0), 'sk')
                    for hring in holes:
                        L += _ring_lines(hring, ind, W_at(z0), 'sk')
                L.append(f"{ind}profs = _pick(sk, {_material_areas_cm2(slab['rings'])})")
                L.append(f"{ind}ei = extrudes.createInput(profs, newBody if first else join)")
                L.append(f"{ind}ei.setDistanceExtent(False, adsk.core.ValueInput.createByReal({_cm(h)}))")
                L.append(f"{ind}extrudes.add(ei)")
                L.append(f"{ind}first = False")
        for c in info.get('cross_cyls', []):
            ax = np.asarray(c['axis'], float)
            bx, by = c['basis']
            c3 = c['center2'][0] * np.asarray(bx) + c['center2'][1] * np.asarray(by)
            blind = c.get('blind', [False, False])
            e0 = 0.0 if blind[0] else 1.0
            e1 = 0.0 if blind[1] else 1.0
            p0 = c3 + ax * (c['h0'] - e0)
            depth = (c['h1'] - c['h0']) + e0 + e1
            L.append(f"{ind}# cross-axis hole r={c['r']:.3f} mm")
            L.append(f"{ind}pl = _plane(root, ({_cm(p0[0])}, {_cm(p0[1])}, {_cm(p0[2])}), ({ax[0]:.6f}, {ax[1]:.6f}, {ax[2]:.6f}))")
            L.append(f"{ind}sk = root.sketches.add(pl)")
            L.append(f"{ind}sk.sketchCurves.sketchCircles.addByCenterRadius("
                     f"sk.modelToSketchSpace(adsk.core.Point3D.create({_cm(p0[0])}, {_cm(p0[1])}, {_cm(p0[2])})), {_cm(c['r'])})")
            L.append(f"{ind}ei = extrudes.createInput(sk.profiles.item(0), cut)")
            L.append(f"{ind}ei.setDistanceExtent(False, adsk.core.ValueInput.createByReal({_cm(depth)}))")
            L.append(f"{ind}extrudes.add(ei)")
        for c in info.get('cones', []):
            L.append(f"{ind}# cross-axis cone (countersink), half-angle {np.degrees(c['half_angle']):.1f} deg: "
                     f"add a Revolve cut or Hole feature manually; apex {np.round(c['apex'], 3).tolist()} mm, "
                     f"axis {np.round(c['axis'], 4).tolist()}, extent {c['h0']:.2f}..{c['h1']:.2f} mm from the apex")
        L.append(f"{ind}made_any = True")
    L += [
        f"{ind}if not made_any:",
        f"{ind}    ui.messageBox('stl2prism: nothing to build (no body was recognised as an extrusion)')",
        '    except:',
        "        if ui:",
        "            ui.messageBox('stl2prism script failed:\\n{}'.format(traceback.format_exc()))",
        '',
    ]
    return '\n'.join(L) + '\n'
